/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { useApp } from '../context/AppContext';
import {
  Search,
  Clock,
  LogIn,
  LogOut,
  Bell,
  Sun,
  Moon,
  StopCircle,
  Sparkles,
  ChevronRight,
  Globe,
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

interface HeaderProps {
  activeModule: string;
  onOpenSearch: () => void;
}

export const Header: React.FC<HeaderProps> = ({ activeModule, onOpenSearch }) => {
  const {
    currentRole,
    currentUserEmployee,
    attendance,
    checkIn,
    checkOut,
    darkMode,
    setDarkMode,
    activeTimerTaskId,
    timerSeconds,
    stopTaskTimer,
    tasks,
    fiverrOrders,
  } = useApp();

  const [localTime, setLocalTime] = useState<string>('');
  const [utcTime, setUtcTime] = useState<string>('');
  const [showNotifications, setShowNotifications] = useState(false);

  // Time zone clocks updater
  useEffect(() => {
    const updateClocks = () => {
      const now = new Date();
      setLocalTime(now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }));
      setUtcTime(
        now.toLocaleTimeString([], { timeZone: 'UTC', hour: '2-digit', minute: '2-digit', hour12: false }) + ' UTC'
      );
    };
    updateClocks();
    const interval = setInterval(updateClocks, 1000);
    return () => clearInterval(interval);
  }, []);

  // Format running timesheet duration
  const formatDuration = (secs: number) => {
    const h = Math.floor(secs / 3600);
    const m = Math.floor((secs % 3600) / 60);
    const s = secs % 60;
    return [h, m, s].map((v) => (v < 10 ? '0' + v : v)).join(':');
  };

  const activeTimerTask = tasks.find((t) => t.id === activeTimerTaskId);

  // Resolve today's attendance state
  const todayStr = new Date().toISOString().split('T')[0];
  const todayRecord = attendance.find((r) => r.employeeId === currentUserEmployee?.id && r.date === todayStr);

  const isCheckedIn = !!todayRecord;
  const isCheckedOut = !!todayRecord?.checkOut;

  // Notification items resolver
  const mockNotifications = [
    { id: 'n-1', text: '🔔 Fiverr order #FO9902A3 requires review from lead designer.', time: '10m ago', unread: true },
    { id: 'n-2', text: '📈 Profit margins report generated by Gemini AI.', time: '1h ago', unread: true },
    { id: 'n-3', text: '⚠️ Project "Epic Travel" delivery is tomorrow.', time: '2h ago', unread: false },
  ];

  const unreadCount = mockNotifications.filter((n) => n.unread).length;

  const moduleDisplayNames: Record<string, string> = {
    dashboard: 'Agency Dashboard',
    employees: 'Employee Directory',
    fiverr: 'Fiverr Orders Workspace',
    projects: 'Projects & Tasks',
    attendance: 'Attendance Management',
    timesheets: 'Timesheets Log',
    standups: 'Daily Standup Reports',
    finance: 'Financial Workspace',
    assets: 'Assets Inventory',
    wiki: 'Knowledge Base & SOPs',
    chat: 'Interactive Chat',
  };

  return (
    <header className="h-[64px] border-b border-slate-200/80 dark:border-slate-800/80 bg-white/85 dark:bg-slate-900/85 backdrop-blur-md px-6 flex items-center justify-between relative z-40 select-none">
      {/* Breadcrumb Module Title */}
      <div className="flex items-center space-x-2">
        <span className="text-xs font-semibold text-slate-400 font-mono">OfficeFlow</span>
        <ChevronRight className="w-3.5 h-3.5 text-slate-300 dark:text-slate-700" />
        <span className="text-sm font-bold text-slate-800 dark:text-slate-100 font-display">
          {moduleDisplayNames[activeModule] || 'Workspace'}
        </span>
      </div>

      {/* Global Search trigger bar */}
      <div className="hidden lg:flex items-center max-w-md w-72 relative">
        <button
          onClick={onOpenSearch}
          className="w-full flex items-center justify-between px-3.5 py-1.5 rounded-xl border border-slate-200/60 dark:border-slate-800/60 bg-slate-50/50 dark:bg-slate-950/20 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 hover:border-slate-300 dark:hover:border-slate-700 transition text-left"
        >
          <div className="flex items-center space-x-2">
            <Search className="w-4 h-4 text-slate-400" />
            <span className="text-xs">Search projects, tasks...</span>
          </div>
          <div className="flex items-center space-x-1 border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 px-1.5 py-0.5 rounded text-[9px] font-mono font-medium">
            <span>⌘K</span>
          </div>
        </button>
      </div>

      {/* Utility Area */}
      <div className="flex items-center space-x-4">
        {/* Live Running Timesheet Ticker */}
        <AnimatePresence>
          {activeTimerTaskId && activeTimerTask && (
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 20 }}
              className="flex items-center space-x-2 px-3 py-1.5 rounded-xl border border-rose-100 dark:border-rose-950/30 bg-rose-50/50 dark:bg-rose-950/10 text-rose-600"
            >
              <Clock className="w-4 h-4 animate-spin text-rose-500 shrink-0" />
              <div className="text-left leading-none max-w-[120px] md:max-w-[200px]">
                <p className="text-[9px] uppercase tracking-wider font-mono font-bold text-rose-400">TRACKING TIME</p>
                <p className="text-xs font-semibold truncate text-rose-700 dark:text-rose-300">{activeTimerTask.title}</p>
              </div>
              <span className="text-xs font-mono font-bold">{formatDuration(timerSeconds)}</span>
              <button
                onClick={() => stopTaskTimer('')}
                className="p-1 rounded-lg hover:bg-rose-100 dark:hover:bg-rose-950/40 text-rose-500 hover:text-rose-700 transition shrink-0"
                title="Stop Timer and Log"
              >
                <StopCircle className="w-4.5 h-4.5 fill-current" />
              </button>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Global Clocks (Local and UTC) */}
        <div className="hidden xl:flex items-center space-x-4 border-r border-slate-100 dark:border-slate-800 pr-4 text-slate-500 dark:text-slate-400">
          <div className="flex items-center space-x-1.5 text-xs font-medium font-mono">
            <Clock className="w-3.5 h-3.5 text-blue-500" />
            <span>{localTime}</span>
          </div>
          <div className="flex items-center space-x-1.5 text-xs font-medium font-mono">
            <Globe className="w-3.5 h-3.5 text-slate-400" />
            <span>{utcTime}</span>
          </div>
        </div>

        {/* Quick Check-In / Check-Out */}
        {currentUserEmployee && (
          <div className="flex items-center">
            {!isCheckedIn ? (
              <button
                onClick={checkIn}
                className="flex items-center px-3 py-1.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold shadow-sm shadow-blue-500/10 transition cursor-pointer"
              >
                <LogIn className="w-3.5 h-3.5 mr-1.5" /> Check In
              </button>
            ) : !isCheckedOut ? (
              <button
                onClick={checkOut}
                className="flex items-center px-3 py-1.5 rounded-xl border border-slate-200 dark:border-slate-800 hover:bg-slate-50 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-300 text-xs font-semibold transition cursor-pointer"
              >
                <LogOut className="w-3.5 h-3.5 mr-1.5 text-rose-500" /> Check Out
              </button>
            ) : (
              <span className="text-[10px] px-2.5 py-1 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-400 font-bold font-mono">
                OUT FOR TODAY
              </span>
            )}
          </div>
        )}

        {/* Theme Toggle */}
        <button
          onClick={() => setDarkMode(!darkMode)}
          className="p-2 rounded-xl border border-slate-200/60 dark:border-slate-800/60 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-800 transition"
        >
          {darkMode ? <Sun className="w-4 h-4 text-amber-400" /> : <Moon className="w-4 h-4 text-slate-500" />}
        </button>

        {/* Real-time Notifications Bell */}
        <div className="relative">
          <button
            onClick={() => setShowNotifications(!showNotifications)}
            className="p-2 rounded-xl border border-slate-200/60 dark:border-slate-800/60 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-800 transition"
          >
            <Bell className="w-4 h-4" />
            {unreadCount > 0 && (
              <span className="absolute top-1.5 right-1.5 w-2 h-2 rounded-full bg-rose-500 ring-2 ring-white dark:ring-slate-900" />
            )}
          </button>

          {/* Notifications Dropdown Panel */}
          <AnimatePresence>
            {showNotifications && (
              <>
                <div className="fixed inset-0 z-45" onClick={() => setShowNotifications(false)} />
                <motion.div
                  initial={{ opacity: 0, y: 10, scale: 0.95 }}
                  animate={{ opacity: 1, y: 0, scale: 1 }}
                  exit={{ opacity: 0, y: 10, scale: 0.95 }}
                  className="absolute right-0 mt-2 w-80 rounded-2xl border border-slate-100 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-2xl z-50 p-4"
                >
                  <div className="flex items-center justify-between pb-3 border-b border-slate-50 dark:border-slate-800">
                    <span className="text-xs font-bold font-display text-slate-800 dark:text-slate-200">Agency Signals</span>
                    <span className="text-[10px] px-2 py-0.5 rounded-full bg-blue-50 dark:bg-blue-950/40 text-blue-600 dark:text-blue-400 font-mono font-semibold">
                      {unreadCount} unread
                    </span>
                  </div>
                  <div className="mt-2 space-y-2.5">
                    {mockNotifications.map((noti) => (
                      <div
                        key={noti.id}
                        className={`p-2.5 rounded-xl text-xs transition ${
                          noti.unread ? 'bg-blue-50/40 dark:bg-blue-950/10' : 'hover:bg-slate-50 dark:hover:bg-slate-800/30'
                        }`}
                      >
                        <p className="text-slate-700 dark:text-slate-300 leading-normal">{noti.text}</p>
                        <span className="text-[10px] text-slate-400 mt-1 font-mono block">{noti.time}</span>
                      </div>
                    ))}
                  </div>
                </motion.div>
              </>
            )}
          </AnimatePresence>
        </div>
      </div>
    </header>
  );
};
